export const generalStyles = {
  paddingTinyer: 4,
  paddingTiny: 6,
  paddingSmaller: 8,
  paddingSmall: 12,
  paddingMedium: 16,
  paddingBig: 20,
  paddingLarge: 24,
  paddingMassive: 28,
  paddingForNotch: 48,
  marginTiny: 4,
  marginSmaller: 8,
  marginSmall: 12,
  marginMedium: 16,
  marginBig: 20,
  marginLarge: 24,
  marginMassive: 28,
  generalRadius: 8,
};
